import { StyleSheet } from "react-native";

export const adminStyles = StyleSheet.create({
  container: { flex: 1 },
  backButton: {
    position: "absolute",
    left: 20,
    zIndex: 10,
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  header: { paddingHorizontal: 20, paddingBottom: 15 },
  headerTitle: { fontSize: 24, fontWeight: "bold", marginBottom: 4 },
  headerSubtitle: { fontSize: 12, fontWeight: "500" },
  tabsContainer: {
    flexDirection: "row",
    borderBottomWidth: 1,
    paddingHorizontal: 20,
  },
  tab: { flex: 1, paddingVertical: 15, alignItems: "center" },
  tabText: { fontSize: 14 },
  contentContainer: { flex: 1, paddingHorizontal: 20, paddingVertical: 15 },
  centerContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 15,
    gap: 10,
  },
  searchInput: { flex: 1, fontSize: 14 },
  addButton: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    marginBottom: 15,
    alignItems: "center",
    gap: 8,
  },
  addButtonText: { color: "#000", fontWeight: "700", fontSize: 14 },
  itemCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
  },
  itemInfo: { flex: 1 },
  idBadge: {
    backgroundColor: "#D4AF37",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    alignSelf: "flex-start",
    marginBottom: 6,
  },
  idBadgeText: { color: "#000", fontSize: 10, fontWeight: "bold" },
  itemName: { fontSize: 16, fontWeight: "700", marginBottom: 4 },
  itemDetail: { fontSize: 12, marginBottom: 2 },
  itemActions: { flexDirection: "row", gap: 8 },
  actionButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  modal: { flex: 1 },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
  },
  modalTitle: { fontSize: 20, fontWeight: "700" },
  modalContent: { flex: 1 },
  modalForm: { paddingHorizontal: 20, paddingVertical: 20, paddingBottom: 40 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 15,
    marginTop: 5,
  },
  label: { fontSize: 14, fontWeight: "600", marginBottom: 8 },
  themeToggleButton: {
    position: "absolute",
    zIndex: 10,
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  input: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 16,
    fontSize: 14,
  },
  row: { flexDirection: "row", justifyContent: "space-between" },
  productInputRow: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 16,
  },
  productInputColumn: {
    flex: 1,
  },
  helperText: {
    fontSize: 12,
    marginTop: -8,
    marginBottom: 16,
  },
  kgHelperRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  kgLimitBadge: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
    marginTop: -8,
    marginBottom: 16,
  },
  tipsBox: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 14,
    marginTop: 18,
  },
  tipsTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  tipsTitle: {
    fontSize: 15,
    fontWeight: "700",
  },
  tipText: {
    fontSize: 13,
    lineHeight: 22,
  },
  typeSelector: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  typeButton: {
    flex: 1,
    minWidth: "48%",
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
  },
  typeButtonText: { fontWeight: "600", fontSize: 12 },
  submitButton: {
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
  },
  submitButtonText: { color: "#000", fontWeight: "700", fontSize: 16 },
  breedSelector: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  breedButton: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  breedButtonText: { fontSize: 12, fontWeight: "600" },
  ageSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 16,
  },
  ageButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  ageText: { fontSize: 18, fontWeight: "700" },
  emptyText: { textAlign: "center", marginTop: 20, fontSize: 14 },
  imagePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderRadius: 8,
    borderStyle: "dashed",
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 12,
  },
  imagePickerText: {
    fontSize: 14,
    fontWeight: "600",
  },
  imagePreviewContainer: {
    position: "relative",
    marginBottom: 12,
    borderRadius: 10,
    overflow: "hidden",
    alignSelf: "flex-start",
  },
  imagePreview: {
    width: 160,
    height: 120,
    borderRadius: 10,
  },
  removeImageButton: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  // Dashboard specific styles
  dashboardCard: {
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
  },
  dashboardCardTitle: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 12,
  },
  dashboardGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  dashboardGridItem: {
    flex: 1,
    padding: 12,
    borderRadius: 10,
    alignItems: "center",
    borderWidth: 1,
  },
  dashboardGridValue: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 4,
  },
  dashboardGridLabel: {
    fontSize: 12,
    textAlign: "center",
  },
  listItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  listItemTitle: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 4,
  },
  listItemSubtitle: {
    fontSize: 12,
  },
});
